# Introduction to Numpy and Basic Array (Data Analysis only)

## What is NumPy?  
- Python library for numerical computing
- Provides array, metrices, and mathematical functions
- Mostly used in Data Analysis, Data Science and Machine Learning

## Installing Numpy
```python
pip install numpy
```

## Creating Array

In [34]:
# importing numpy with alias
import numpy as np

In [35]:
# creating 1D array 
arr1d = np.array([1,2,3,4,5,6])
print("1D array : ", arr1d)

1D array :  [1 2 3 4 5 6]


In [36]:
# creating 2D array
arr2d = np.array([[1,2,3],[4,5,6]])
print("2D array: \n", arr2d)

2D array: 
 [[1 2 3]
 [4 5 6]]


In [37]:
# creating array with zeros
# zeros = np.zeros(10)             # 10 rows with zeros only
zeros = np.zeros([2,3])          # 2 rows, 3 columns
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [38]:
# creating array with ones
ones = np.ones([3,2])           # 3 rows, 2 columns
ones

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [39]:
# creating array with range of numbers (1D Array)
range_arr = np.arange(10)
range_arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [40]:
# creating array with range of numbers (2D Array)
range_arr1 = np.arange(1, 4)
range_arr2 = np.arange(4, 7)

new_arr2D = np.vstack([range_arr1, range_arr2])
new_arr2D

array([[1, 2, 3],
       [4, 5, 6]])

In [41]:
# creating array with evenly spaced numbers
linspace = np.linspace(0,1,5)                 # 5 numbers from 0 to 1
linspace

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

## Basic Operation

In [43]:
arr1d.shape        # Returns 6 rows and 0 columns    

(6,)

In [45]:
arr2d.shape        # Returns 2 rows and 3 columns

(2, 3)

In [47]:
arr1d.ndim         # Returns dimension of the array

1

In [49]:
arr2d.ndim         # Returns dimension of the array

2

In [52]:
arr1d.dtype        # Returns datatype of the array

dtype('int32')

## Indexing and Slicing

In [55]:
arr1d = np.array([1,2,3,4,5,6])
arr2d = np.array([[1,2,3],[4,5,6]])

In [61]:
arr1d[0]          # 0 index returns a value from the array in 1D array

1

In [62]:
arr2d[0]          # 0 Returns 1st row from 2D array

array([1, 2, 3])

In [64]:
# access specific value from 2D array
arr2d[1][2]       # Return a value from 2nd row and 3rd element because in python 0 index means 1st position.

6

In [67]:
# slicing (selecting multiple values from the array)
arr1d[1:4]        # Starts from 1 index (2nd element) and go till 4th position (it starts from 1).

array([2, 3, 4])

In [76]:
arr2d[0][0:2]

array([1, 2])

In [79]:
arr2d[:, 1:3]

array([[2, 3],
       [5, 6]])

## Exercise:
- Create a 3D array of shape (2, 2, 2) filled with ones.
- Create an array with numbers from 5 to 15 using np.arange().
- Print the shape, number of dimensions, and data type of your created arrays.

In [89]:
# Create a 3D array of shape (2, 2, 2) filled with ones.
ones_3D = np.ones([2,2,2], dtype = np.int32)
ones_3D

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [90]:
# Create an array with numbers from 5 to 15 using np.arange().
new_range_arr = np.arange(5, 15)
new_range_arr

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [91]:
# Print the shape, number of dimensions, and data type of your created arrays.
print(f"Shape : {ones_3D.shape}\nDimensions : {ones_3D.ndim}\nDataType : {ones_3D.dtype}")

Shape : (2, 2, 2)
Dimensions : 3
DataType : int32


## Homework
- Practice creating arrays and using attributes. Try out more slicing and indexing techniques.